<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'org\\bovigo\\vfs\\' => array($vendorDir . '/mikey179/vfsStream/src/main/php'),
    'TYPO3\\Welcome' => array($baseDir . '/Packages/Framework/TYPO3.Welcome/Classes'),
    'TYPO3\\Party' => array($baseDir . '/Packages/Framework/TYPO3.Party/Classes'),
    'TYPO3\\Kickstart' => array($baseDir . '/Packages/Framework/TYPO3.Kickstart/Classes'),
    'TYPO3\\Fluid' => array($baseDir . '/Packages/Framework/TYPO3.Fluid/Classes'),
    'TYPO3\\Flow' => array($baseDir . '/Packages/Framework/TYPO3.Flow/Classes'),
    'TYPO3\\Eel' => array($baseDir . '/Packages/Framework/TYPO3.Eel/Classes'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\DomCrawler\\' => array($vendorDir . '/symfony/dom-crawler'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Doctrine\\ORM' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src'),
    'Doctrine\\DBAL\\Migrations' => array($vendorDir . '/doctrine/migrations/lib'),
    'Doctrine\\DBAL' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Doctrine\\Common\\' => array($vendorDir . '/doctrine/common/lib'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src'),
);
